export const DEMO_DATA = {
  programName: "UOX Program",
  weekOf: "2026-04-20",
  generatedAt: new Date().toISOString(),
  scorecards: [
    { label: "Overall RAG",        value: "AMBER", rag: "amber", subtext: "3 critical items open" },
    { label: "Open Risks",         value: "27",    rag: "red",   subtext: "+3 vs last week" },
    { label: "Milestones At Risk", value: "4",     rag: "amber", subtext: "of 21 total" },
    { label: "Open Issues",        value: "14",    rag: "amber", subtext: "stable week-on-week" },
    { label: "Artifacts Complete", value: "61%",   rag: "amber", subtext: "of gate artifacts" },
    { label: "Actions Overdue",    value: "6",     rag: "red",   subtext: "require attention" },
  ],
  executiveSummary: [
    { color: "red",   text: "MDM integration timeline is at high risk — vendor delivery of the data mapping spec is now 3 weeks late, threatening the Q2 cutover date for WGL billing." },
    { color: "red",   text: "Resource constraint critical: two senior SAP functional consultants are double-booked across SEMCO FI and WGL MM workstreams through end of May; escalation to Delivery Lead required this week." },
    { color: "amber", text: "SteerCo gate review for Phase 2 is scheduled for May 7; four gate artifacts remain in-progress and risk a gate deferral if not completed by Apr 30." },
    { color: "amber", text: "SEMCO OT/IT integration dependency on legacy SCADA data feeds remains unresolved; vendor SLA response outstanding since Apr 9." },
    { color: "green", text: "WGL Change Management workstream completed stakeholder impact assessment on schedule; readiness survey deployed to 340 field staff with 72% response rate." },
  ],
  topRisks: [
    {
      id: "R-014",
      project: "WGL Billing / MDM",
      description: "MDM vendor (Itron) has not delivered data mapping specification; delays cutover testing by minimum 3 weeks.",
      level: "H", type: "Schedule", trend: "escalated",
      triggerDate: "2026-05-01", owner: "D. Patel",
      mitigation: "Escalated to vendor account exec; daily stand-up instituted; exploring parallel path with in-house mapping team.",
    },
    {
      id: "R-021",
      project: "Cross-Program",
      description: "Two SAP functional SMEs required on both SEMCO FI cutover and WGL MM parallel run simultaneously in May.",
      level: "H", type: "Resource", trend: "escalated",
      triggerDate: "2026-05-06", owner: "S. Kowalski",
      mitigation: "Requesting 2 additional FTEs from PwC bench; evaluating staff augmentation via approved vendor.",
    },
    {
      id: "R-009",
      project: "SEMCO OT/IT Integration",
      description: "Legacy SCADA historian feeds not yet mapped to new PI system; vendor SLA response overdue by 11 days.",
      level: "H", type: "Dependency", trend: "watch",
      triggerDate: "2026-04-30", owner: "M. Reyes",
      mitigation: "Formal cure notice issued Apr 14; fallback manual extract procedure drafted pending SLA resolution.",
    },
    {
      id: "R-033",
      project: "WGL Field Operations",
      description: "Mobile workforce management (MWM) UAT defect backlog at 38 open items; go-live confidence low.",
      level: "M", type: "Technical", trend: "new",
      triggerDate: "2026-05-15", owner: "T. Nguyen",
      mitigation: "Defect triage session scheduled Apr 22; 14 P1 defects targeted for resolution by Apr 28.",
    },
    {
      id: "R-006",
      project: "SEMCO Gas Distribution",
      description: "Regulatory filing deadline for rate case data requires clean ERP data extract by Jun 1; data quality cleanse not started.",
      level: "M", type: "Operational", trend: "stable",
      triggerDate: "2026-06-01", owner: "A. Thornton",
      mitigation: "Data quality sprint kickoff Apr 28; SEMCO regulatory team engaged to confirm minimum viable data set.",
    },
    {
      id: "R-018",
      project: "WGL Finance",
      description: "Chart of accounts harmonisation between WGL and SEMCO entities still has 47 unresolved mapping exceptions.",
      level: "M", type: "Financial", trend: "improving",
      triggerDate: "2026-05-20", owner: "R. Osei",
      mitigation: "Weekly CoA working group in place; exception count reduced from 89 two weeks ago; target <10 by May 9.",
    },
  ],
  milestones: [
    { name: "MDM Data Mapping Spec Received",        project: "WGL MDM",            dueDate: "2026-04-07", rag: "red",   progress: 0,  atRisk: true,  note: "Vendor 3 weeks late; no revised ETA confirmed." },
    { name: "SEMCO FI Parallel Run Start",            project: "SEMCO Finance",      dueDate: "2026-05-06", rag: "amber", progress: 45, atRisk: true,  note: "Resource conflict may push to May 13." },
    { name: "Phase 2 SteerCo Gate Review",            project: "Program Governance", dueDate: "2026-05-07", rag: "amber", progress: 68, atRisk: true,  note: "4 artifacts still in-progress." },
    { name: "WGL MWM UAT Sign-Off",                   project: "WGL Field Ops",      dueDate: "2026-05-15", rag: "amber", progress: 52, atRisk: true,  note: "38 open defects; P1 triage in progress." },
    { name: "Stakeholder Readiness Survey Complete",  project: "Change Management",  dueDate: "2026-04-18", rag: "green", progress: 100, atRisk: false, note: "Completed on schedule. 72% response rate." },
    { name: "CoA Harmonisation Draft Complete",       project: "WGL Finance",        dueDate: "2026-05-09", rag: "green", progress: 75, atRisk: false, note: "47 exceptions remaining; on track." },
    { name: "SCADA Historian Feed Mapping",           project: "SEMCO OT/IT",        dueDate: "2026-04-30", rag: "red",   progress: 10, atRisk: true,  note: "Vendor SLA response outstanding." },
    { name: "SAP Security Role Build Complete",       project: "Cross-Program",      dueDate: "2026-05-20", rag: "green", progress: 80, atRisk: false, note: "On track; final review scheduled May 12." },
    { name: "Data Quality Cleanse Sprint 1",          project: "SEMCO Gas",          dueDate: "2026-05-12", rag: "amber", progress: 0,  atRisk: false, note: "Kickoff Apr 28; not yet started." },
  ],
  artifacts: [
    {
      project: "WGL Billing / MDM",
      items: [
        { gate: "Gate 2", artifact: "Business Requirements Document",    status: "complete",     notes: "Approved Feb 14" },
        { gate: "Gate 2", artifact: "Data Mapping Specification",        status: "overdue",      notes: "Vendor delivery 3 weeks late" },
        { gate: "Gate 2", artifact: "Interface Design Document",         status: "in-progress",  notes: "Draft shared Apr 10; review pending" },
        { gate: "Gate 2", artifact: "UAT Test Scripts",                  status: "not-started",  notes: "Blocked on data mapping" },
        { gate: "Gate 3", artifact: "Cutover Runbook",                   status: "not-started",  notes: "Target start May 1" },
      ],
    },
    {
      project: "SEMCO Finance (FI/CO)",
      items: [
        { gate: "Gate 2", artifact: "Process Design Document — FI-AP",   status: "complete",     notes: "Signed off Mar 28" },
        { gate: "Gate 2", artifact: "Process Design Document — FI-AR",   status: "complete",     notes: "Signed off Apr 2" },
        { gate: "Gate 2", artifact: "Configuration Workbook",            status: "in-progress",  notes: "75% complete; resource constraint" },
        { gate: "Gate 2", artifact: "Integration Test Plan",             status: "pending",      notes: "Awaiting config workbook completion" },
        { gate: "Gate 3", artifact: "Parallel Run Plan",                 status: "in-progress",  notes: "Draft v0.2 circulated" },
      ],
    },
    {
      project: "WGL Field Operations (MWM)",
      items: [
        { gate: "Gate 2", artifact: "Functional Specification",          status: "complete",     notes: "Approved Mar 15" },
        { gate: "Gate 2", artifact: "UAT Test Cases",                    status: "complete",     notes: "204 test cases documented" },
        { gate: "Gate 2", artifact: "UAT Defect Log",                    status: "in-progress",  notes: "38 open defects; triage Apr 22" },
        { gate: "Gate 3", artifact: "Go-Live Readiness Checklist",       status: "not-started",  notes: "Target Apr 30" },
      ],
    },
    {
      project: "Change Management",
      items: [
        { gate: "Gate 2", artifact: "Stakeholder Impact Assessment",     status: "complete",     notes: "Completed Apr 18" },
        { gate: "Gate 2", artifact: "Training Needs Analysis",           status: "complete",     notes: "Completed Apr 5" },
        { gate: "Gate 2", artifact: "Communications Plan",               status: "complete",     notes: "Approved Apr 1" },
        { gate: "Gate 3", artifact: "Training Materials — Wave 1",       status: "in-progress",  notes: "50% complete; due May 15" },
        { gate: "Gate 3", artifact: "Readiness Assessment Report",       status: "pending",      notes: "Depends on survey analysis" },
      ],
    },
  ],
  issueHealth: {
    hh: 6, mh: 10, mm: 11,
    totalRisks: 27, totalIssues: 14,
    newThisWeek: 4, closedThisWeek: 1,
    trend: "deteriorating",
    narrative: "Issue volume increased for the third consecutive week, driven primarily by the MDM vendor delay and the emerging resource constraint across SAP workstreams. The H/H risk count rose from 4 to 6 this week. Only 1 issue was closed, indicating insufficient resolution throughput relative to the rate of new items being raised. Escalation of the two H/H resource and vendor risks to program leadership is recommended before end of week.",
  },
  resourceRisks: "The program faces a critical dual-resource bottleneck in May: two senior SAP functional consultants are required concurrently on SEMCO FI parallel run activities and WGL MM configuration sign-off, with no current bench capacity to cover the gap. A formal request for 2 additional FTE has been submitted to the PwC delivery lead. Additionally, the SEMCO OT/IT workstream PI lead is carrying a 130% utilisation forecast through end of April due to the SCADA mapping issue. Change Management has sufficient resourcing through Phase 2 gate, but will require an additional training developer for Wave 2 content build beginning June. No contractor spend above plan has been approved; any staff augmentation decisions require SteerCo sponsor sign-off.",
  dependencies: [
    { from: "Itron (MDM Vendor)",    to: "WGL Billing Cutover",       risk: "Data mapping spec delivery blocks all downstream testing; no revised date confirmed.",         rag: "red" },
    { from: "SEMCO SCADA / Vendor",  to: "OT/IT PI Integration",      risk: "Historian feed mapping cannot proceed until vendor provides data dictionary; SLA overdue.",     rag: "red" },
    { from: "CoA Harmonisation",     to: "SEMCO FI Parallel Run",     risk: "Unresolved mapping exceptions (47) could invalidate parallel run ledger comparison results.",   rag: "amber" },
    { from: "MWM UAT Sign-Off",      to: "WGL Field Ops Go-Live",     risk: "P1 defect resolution must complete before UAT closure; go-live date contingent on sign-off.",   rag: "amber" },
    { from: "SAP Security Build",    to: "Cross-Program UAT Access",  risk: "Role build 80% complete; delay risks blocking testers from accessing environments in May.",      rag: "green" },
    { from: "Training Materials",    to: "End-User Readiness",        risk: "Wave 1 materials 50% complete; on current trajectory will meet May 15 date for first cohort.",  rag: "green" },
  ],
  changesThisWeek: [
    { type: "risk",      text: "R-014 (MDM Vendor Delay) escalated from AMBER to RED — no revised delivery date received after Apr 14 escalation call; daily vendor stand-up now in effect." },
    { type: "risk",      text: "R-021 (Resource Conflict) raised as new HIGH risk — dual booking of two SAP SMEs confirmed by resource managers Apr 17." },
    { type: "milestone", text: "SEMCO FI Parallel Run Start (May 6) flagged as at-risk due to resource conflict; contingency date of May 13 under discussion." },
    { type: "artifact",  text: "WGL MDM Data Mapping Specification status changed from PENDING to OVERDUE following missed Apr 7 delivery date." },
    { type: "decision",  text: "PwC Delivery Lead approved escalation of vendor SLA breach to WGL executive sponsor; formal cure notice issued Apr 14." },
    { type: "resource",  text: "Staff augmentation request for 2 SAP FI consultants submitted to PwC resourcing; target start date May 4 to cover parallel run gap." },
    { type: "milestone", text: "Stakeholder Readiness Survey marked COMPLETE — 340 field staff surveyed, 72% response rate, results being analysed this week." },
  ],
  actions: [
    { text: "Confirm revised delivery date for MDM data mapping specification from Itron account executive.",               owner: "D. Patel",      due: "2026-04-23" },
    { text: "Submit formal resource request to PwC bench for 2 SAP FI/CO consultants; confirm availability by Apr 25.",    owner: "S. Kowalski",   due: "2026-04-24" },
    { text: "Complete P1 defect triage for MWM UAT and publish revised resolution timeline to workstream lead.",            owner: "T. Nguyen",     due: "2026-04-22" },
    { text: "Schedule CoA harmonisation working session to resolve remaining 47 exceptions; target <10 by May 9.",          owner: "R. Osei",       due: "2026-04-25" },
    { text: "Confirm SEMCO SCADA vendor response on data dictionary; escalate to contract manager if no response by Apr 23.", owner: "M. Reyes",    due: "2026-04-23" },
    { text: "Circulate Phase 2 gate artifact status to workstream leads; confirm completion plan for 4 in-progress items.", owner: "Program PMO",   due: "2026-04-22" },
    { text: "Publish readiness survey analysis summary to Change Management workstream and SteerCo sponsor.",               owner: "L. Fernandez",  due: "2026-04-28" },
    { text: "Review and approve SEMCO FI parallel run contingency plan (May 13 date) with finance workstream lead.",        owner: "S. Kowalski",   due: "2026-04-25" },
  ],
};
